# fly.toml app configuration file generated for weatherman-staging-18-jun-3-14957884-9d6f-48f3-b49f-d48473697199-server on 2024-06-18T15:52:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weatherman-staging-18-jun-3-14957884-9d6f-48f3-b49f-d48473697199-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
